configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/self-a1ndreay%2Fbooking.com-cd84be4af2daddf15226221fddea4b54a91f4d780bb49c9e5f7cf0b39fb3ddf3.yml
openapi_spec_hash: c30a0fa1ea4c3be172e108a709254d5f
config_hash: de09f42daf6a64bb591d24ba72791e23
